# Usa la imagen base oficial de Wazuh
FROM wazuh/wazuh:3.13.6_7.9.2

# Configura el comando por defecto para iniciar el contenedor
CMD ["wazuh-indexer"]

# Expone los puertos necesarios
EXPOSE 55000
EXPOSE 1514/udp
