
services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8123:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
    restart: always
  db:
    build:
      context: ./mariadb
    container_name: mariadb_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
  wazuh:
    image: wazuh/wazuh:3.13.6_7.9.2
    container_name: wazuh_manager
    restart: always
    environment:
      - WAZUH_MANAGER=yes
    ports:
      - "55000:55000"
      - "1514:1514/udp"
    command: wazuh-indexer
    networks:
      - default
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: wazuh_elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" # Configuración de memoria
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always

  kibana:
    image: elastic/kibana:7.17.27
    container_name: wazuh_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: always

volumes:
  mariadb_data:
  elastic_data:
