services:
  nginx:
    build:
      context: ./nginx
    image: username/nginx:latest
    container_name: nginx_server
    ports:
      - "8998:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
    restart: always

  db:
    build:
      context: ./mariadb
    image: username/mariadb:latest
    container_name: mariadb_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  wazuh:
    build:
      context: ./wazuh
    image: username/wazuh-manager:latest
    container_name: wazuh_manager
    restart: always
    ports:
      - "55000:55000"
      - "1514:1514/udp"

volumes:
  mariadb_data:
